{
  "uid" : "430f50d6c6d8ad9",
  "name" : "test_upload_new_article_from_file",
  "fullName" : "test.test_TC06_AdatsorozatFile.TestFileUpload#test_upload_new_article_from_file",
  "historyId" : "403c15492746c0c397461b17783d0580",
  "time" : {
    "start" : 1628660127003,
    "stop" : 1628660128849,
    "duration" : 1846
  },
  "status" : "broken",
  "statusMessage" : "FileNotFoundError: [Errno 2] No such file or directory: 'data.csv'",
  "statusTrace" : "self = <test_TC06_AdatsorozatFile.TestFileUpload object at 0x7fb8ca0b1b20>\n\n    def test_upload_new_article_from_file(self):\n        conduit_login(self.driver)\n        WebDriverWait(\n            self.driver, 15).until(\n            EC.element_to_be_clickable((By.XPATH, \"//h1[normalize-space()='Recipe']\"))\n        )\n        first_article = self.driver.find_element_by_xpath(\"//h1[normalize-space()='Recipe']\")\n        first_article.click()\n        element = WebDriverWait(\n            self.driver, 10).until(\n            EC.visibility_of_element_located((By.XPATH, \"//textarea[@placeholder='Write a comment...']\"))\n            )\n>       with open('data.csv', 'r', encoding=\"utf-8\") as csvfile:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'data.csv'\n\ntest/test_TC06_AdatsorozatFile.py:36: FileNotFoundError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "testStage" : {
    "status" : "broken",
    "statusMessage" : "FileNotFoundError: [Errno 2] No such file or directory: 'data.csv'",
    "statusTrace" : "self = <test_TC06_AdatsorozatFile.TestFileUpload object at 0x7fb8ca0b1b20>\n\n    def test_upload_new_article_from_file(self):\n        conduit_login(self.driver)\n        WebDriverWait(\n            self.driver, 15).until(\n            EC.element_to_be_clickable((By.XPATH, \"//h1[normalize-space()='Recipe']\"))\n        )\n        first_article = self.driver.find_element_by_xpath(\"//h1[normalize-space()='Recipe']\")\n        first_article.click()\n        element = WebDriverWait(\n            self.driver, 10).until(\n            EC.visibility_of_element_located((By.XPATH, \"//textarea[@placeholder='Write a comment...']\"))\n            )\n>       with open('data.csv', 'r', encoding=\"utf-8\") as csvfile:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'data.csv'\n\ntest/test_TC06_AdatsorozatFile.py:36: FileNotFoundError",
    "steps" : [ ],
    "attachments" : [ {
      "uid" : "d73909d8b3de5be6",
      "name" : "log",
      "source" : "d73909d8b3de5be6.txt",
      "type" : "text/plain",
      "size" : 344
    }, {
      "uid" : "8c377916c8196168",
      "name" : "stderr",
      "source" : "8c377916c8196168.txt",
      "type" : "text/plain",
      "size" : 215
    } ],
    "parameters" : [ ],
    "stepsCount" : 0,
    "attachmentsCount" : 2,
    "shouldDisplayMessage" : true,
    "hasContent" : true
  },
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "parentSuite",
    "value" : "test"
  }, {
    "name" : "suite",
    "value" : "test_TC06_AdatsorozatFile"
  }, {
    "name" : "subSuite",
    "value" : "TestFileUpload"
  }, {
    "name" : "host",
    "value" : "fv-az47-289"
  }, {
    "name" : "thread",
    "value" : "3787-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "test.test_TC06_AdatsorozatFile"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ ]
  },
  "source" : "430f50d6c6d8ad9.json",
  "parameterValues" : [ ]
}